# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af422c13b9f2c802792fa73e1bebe0f2ac72932d96db230008ff60ecf9a87587e7f8ef677920df5e5885d4e882da9176b6e70092b270bcde0cbcc61ccebace59

test:
  secret_key_base: 0212faf7422d3d9fd9628688d578dbd4294cfa84ed0f61e918b9bbedecb63f3074cebeb5600145894f8303a4563f9ff5a818e1a03bbabd0343b8c18dae933ad9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: goodfriend_2014
